{% set name = "econ-ark" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5d2264d3fc1281055faf252407230fd4aa75bad7f9e868cca50917dff17da24d

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3

  run:
    - python >=3
    - quantecon
    - interpolation
    - numba
    - joblib
    - matplotlib-base
    - numpy
    - scipy
    - xarray

test:
  imports:
    - HARK
    - HARK.tests

about:
  home: https://github.com/econ-ark/HARK
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Heterogenous Agents Resources & toolKit

extra:
  recipe-maintainers:
    - MridulS
    - shaunagm
    - sbenthall
